# Generated by Django 6.0 on 2025-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroEcommerce', '0004_vendor_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
