# Generated by Django 6.0 on 2025-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroEcommerce', '0005_alter_farmerproduct_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
